In [1]:
import numpy as np


In [2]:
y_=np.array([-0.693147,-0.510826,-0.356675]).reshape((3,1))
A=np.array([50,-100,50,-65,120,-55,21,-35,15]).reshape((3,3))


In [6]:
k_=A.dot(y_)
k_

array([[-1.4085  ],
       [ 3.37256 ],
       [-2.027302]])

In [7]:
def fun(k_,x):
    res=0
    for k in k_:
        res=res*x+k
    return res


In [9]:
fun(k_,0.5)

array([-0.693147])

In [10]:
fun(k_,0.6)

array([-0.510826])

In [11]:
fun(k_,0.7)

array([-0.356675])

In [12]:
fun(k_,0.54)

array([-0.6168382])